src/cmd/terraform.go

This change is subpar for the user in terms of final configuration but it creates a better first time experience with `terraform plan` which we decided was better in the end.

bugfix: if multiline string from opslevel does not end with \n then have terraform treat it as an escaped string

---

changes/unreleased/Refactor-20220207-213752.yaml
src/cmd/account.go
src/cmd/check.go
src/cmd/deploy.go
src/cmd/filter.go
src/cmd/integration.go
src/cmd/repository.go
src/cmd/root.go
src/cmd/rubric.go
src/cmd/service.go
src/cmd/team.go

This converts the logic to only build the clients when a command actually uses them.  So commands like `opslevel version` don't error out with 
```
Error: Client Validation Error: Please provide a valid OpsLevel API token via 'export OPSLEVEL_API_TOKEN=XXX' or '--api-token=XXX'
```

only build the client when needed

---

.changes/unreleased/Feature-20220604-085836.yaml
src/cmd/team.go
src/cmd/user.go
src/go.mod

This adds the create, list and delete user commands because the opslevel-go portion is now implemented.
I'm leaving off get user because it requires a user ID and thats not a great UX.  The API will eventually support looking up an user by email so once we do that we will implement that in the CLI.

Add User commands

---

src/cmd/group.go
src/cmd/import.go
src/cmd/service.go
src/cmd/team.go
src/cmd/user.go
src/common/csv.go

Add a bunch of CSV import commands that customer success has been asking for.
```
❯ opslevel import -h
Import data to OpsLevel.
Usage:
opslevel import [command]
Available Commands:
group       Imports groups from a CSV
service     Imports services from a CSV
team        Imports teams from a CSV
user        Imports users from a CSV
```
usage examples
```
❯ cat << EOF | opslevel import user -f -
Name,Email,Role,Team
Kyle Rockman,kyle@opslevel.com,Admin,platform
Edgar Ochoa,edgar@opslevel.com,Admin,platform
Adam Del Gobbo,adam@opslevel.com,User,sales
EOF
```
and
```
❯ cat << EOF | opslevel import teams -f -
Name,Manager,Responsibilities,Group
Platform,kyle@opslevel.com,Makes Tools,engineering
Sales,john@opslevel.com,Sells Tools,product
EOF
```
and
```
❯ cat << EOF | opslevel import group -f …
```

Add CSV import commands

---

.changes/unreleased/Feature-20220819-123306.yaml
src/cmd/policy.go
src/go.mod

Example:
```
$ cat maturity-check.rego 
package opslevel
import future.keywords
default can_deploy_dev := false
default can_deploy_staging := false
alias := opslevel.service_maturity_level("cert-manager")["Alias"]
index := opslevel.service_maturity_level("cert-manager")["Index"]
can_deploy_dev {
index >= 0
}
can_deploy_staging {
alias == "silver"
}
$ go run main.go run policy -f maturity-check.rego
{"alias":"beginner","can_deploy_dev":true,"can_deploy_staging":false,"index":0}
```

Add function to check maturity level of a service

---

.changes/unreleased/Bugfix-20220830-104401.yaml
src/cmd/terraform.go

Tested with export and got the expected predicate:
```
resource "opslevel_filter" "single_line_filter" {
name = "Single Line Filter"
connective = ""
predicate {
key = "language"
key_data = ""
type = "equals"
value = "Kotlin"
}
}
```

Fix single line filter exports

---

.changes/unreleased/Feature-20220823-105915.yaml
src/cmd/policy.go

```
$ cat gitlab-repo.rego 
package opslevel
import future.keywords
contains_value(input_list, value) {
contains(input_list[_], value)
}
repo_name := opslevel.repo.gitlab("jklabsinc/OpsLevel")["name"]
repo_description := opslevel.repo.gitlab("jklabsinc/OpsLevel")["description"]
repo_languages := opslevel.repo.gitlab("jklabsinc/OpsLevel")["languages"]
$ go run main.go run policy -f gitlab-repo.rego                   
{"repo_description":"Source for app.opslevel.com.   Level up your DevOps teams.","repo_languages":{"CSS":1.91,"HTML+ERB":0.41,"JavaScript":26.03,"Ruby":59.17,"Vue":11.95},"repo_name":"OpsLevel"}
```

Add Rego function to get gitlab project metadata

---

.changes/unreleased/Feature-20220908-174140.yaml
src/cmd/service.go

This simple patch allows the `opslevel delete service tag` command to accept a tag id in addition to a tag name.

Allow tags to be deleted by ID

---

.changes/unreleased/Feature-20220921-224448.yaml
.changes/unreleased/Feature-20220921-224514.yaml
src/cmd/policy.go

This add 2 new flags to the `opslevel run policy` command
`-i ./input.json` - which allows for passing in extra JSON input for use in the policy at `input.data`
`-o ./output.json` - which allows for directly writing all policy evaluation data to a file so it doesn't get intermixed with other output from loggers
A full example would be:
```
cat << EOF > policy.rego
package opslevel
import future.keywords
value := input.data.foo.Can.nest
EOF
cat << EOF > input.json
{"foo": {"Can": {"nest": true}}}
EOF
opslevel run policy -f policy.rego -i input.json -o output.json 
cat output.json
{"value":true}
```

Add 2 features needed for “Magic Catalog”

---

src/cmd/graphql.go

after doing some more testing i found a bug with key=value parsing and this change makes it make the most sense.
I also added a really cool example of showing how to use the internal API to download the opslevel.yml file for a service

fix graphql command and add another example

---

.changes/unreleased/Bugfix-20230619-172139.yaml
src/cmd/check.go
src/common/output.go
src/common/output_test.go

- create `json.Encoder` to customize `SetEscapeHTML` and `SetIndent` to print `rawNotes` without escaping these following chars:
- "<", ">", "&", U+2028, and U+2029 are escaped to "\u003c","\u003e", "\u0026", "\u2028", and "\u2029"
this misbehaviour was discovered during investigation from this [ticket](https://gitlab.com/jklabsinc/OpsLevel/-/issues/7693)

PrettyPrint no longer escapes html

---

.changes/unreleased/Feature-20230713-231641.yaml
src/cmd/aliases.go

Infrastructure resources have no way to set the alias on them but it seems that `aliasCreate` can do it so i'm adding these commands to the CLI so you can manage aliases on infrastructure resources as well as other things.

Add alias create and delete commands

---

src/cmd/graphql.go

Fixes a panic (see #126) in `opslevel graphql` when you attempt to paginate over a response with `"endCursor": null`. This can be triggered with the following script (assuming there's no team with alias `"does-not-exist"`):
#!/bin/bash
QUERY='query($endCursor: String) {
account {
services(ownerAlias: "does-not-exist", after: $endCursor) {
pageInfo {
endCursor
hasNextPage
}
nodes {
name
}
}
}
}'
opslevel graphql --paginate --query "$QUERY"
Sample panic from running that script before this change:
$ OPSLEVEL_API_TOKEN=<redacted> ./script
panic: runtime error: index out of range [1] with length 0
goroutine 1 [running]:
github.com/opslevel/cli/cmd.glob..func21(0x17c9400?, {0xf6e323?, 0x3?, 0x3?})
/home/user/src/opslevel-cli/src/cmd/graphql.go:145 +0xb0c …

Fix panic when paginating on empty GQL response

---

.changes/unreleased/Bugfix-20230726-195424.yaml
src/cmd/check.go
src/cmd/create.go
src/cmd/dependency.go
src/cmd/deploy.go
src/cmd/document.go
src/cmd/domain.go
src/cmd/group.go
src/cmd/input.go
src/cmd/service.go
src/cmd/system.go
src/cmd/team.go
src/cmd/update.go
src/cmd/user.go

Blocks https://github.com/OpsLevel/cli/pull/139
Bug: `opslevel update $RESOURCE -f $CONFIG.yaml` will not read the input YAML file, unless you pass `-`. This happens for resources like `domains` which don't have a separate input file reading function call. [See example in domain.go](https://github.com/OpsLevel/cli/blob/842ae0260021d1bfc45ba5e63282749a29806c77/src/cmd/domain.go#L141) where creating a domain using a YAML file works but updating one does not.
`-f -` (stdin) is able to work because of persistent flags set in [create.go](https://github.com/OpsLevel/cli/blob/842ae0260021d1bfc45ba5e63282749a29806c77/src/cmd/create.go#L22) and [update.go.](https://github.com/OpsLevel/cli/blob/842ae0260021d1bfc45ba5e63282749a29806c77/src/cmd/update.go#L21)
Merge file reading functions from …

Bugfix for reading YAML files on update

---

.changes/unreleased/Bugfix-20230801-165131.yaml
src/cmd/input.go

The `hasStdIn()` call evaluates to `true` on macOS but `false` in Linux containers. It's not clear why this happens, but logically speaking if the user passed `-f -` they want to read from `stdin`, so it's not necessary to check for it in this case.
As a result, trying to create any resource using a heredoc and YAML will either fail or result in a weird request being sent to the server where none of the intended data was sent. This happens when using containers, or at least the Docker container we have for CLI.
Previously we didn't have this bug happen during `update` operations because they didn't include this check. Only `create` operations were affected. [Source Code](https://github.com/OpsLevel/cli/pull/141/files#diff-f7a74bdb21647930a3ab58b74971361aeb9c65bac68220b6847175119795c646L27) …

Remove stdin check when reading YAML input

---

.changes/unreleased/Feature-20230811-151612.yaml
.changes/unreleased/Feature-20230811-151626.yaml
src/cmd/action.go
src/cmd/trigger_definition.go

Allow CLI users to create webhook actions and trigger definitions!
```
$ go run main.go create action -f action_create.yaml
created webhook action: Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8yMjY
```
```
$ go run main.go update action Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8yMjY -f action_update.yaml
{
"Aliases": [],
"Id": "Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8yMjY",
"Description": "Pages the oncall and creates an incident",
"LiquidTemplate": "",
"Name": "Page The On Call",
"Headers": "{\"accept\":\"application/vnd.pagerduty+json;version=2\",\"authorization\":\"Token token=XXXXXXXXXXXXX\",\"from\":\"someone-else@example.com\"}",
"HTTPMethod": "POST",
"WebhookURL": "https://api.pagerduty.com/incidents"
} …
```

Add support for Webhook Actions and Trigger Definitions

---

.changes/unreleased/Bugfix-20230922-140819.yaml
.changes/unreleased/Feature-20230922-140908.yaml
src/cmd/tag.go

Can find tags where `key == KEY`.
```
$ opslevel get tag --type team $PLATFORM newkey
[
{
"id": "Z2lkOi8vb3BzbGV2ZWwvVGFnLzYwMTgwNTc3",
"key": "newkey",
"value": "newvalue"
},
{
"id": "Z2lkOi8vb3BzbGV2ZWwvVGFnLzYwMTgwNTgx",
"key": "newkey",
"value": "secondvalue"
}
]
```
Will not error out if no keys match `KEY`, will instead output empty JSON array.
```
$ opslevel get tag --type team $PLATFORM nonexistantkey
[]
```
Should be able to output all tags.
```
$ opslevel list tags --type team $PLATFORM
[
{
"id": "Z2lkOi8vb3BzbGV2ZWwvVGFnLzYwMTgwNTc3",
"key": "newkey",
"value": "newvalue"
},
{
"id": "Z2lkOi8vb3BzbGV2ZWwvVGFnLzYwMTgwNTgx",
"key": "newkey",
"value": "secondvalue"
},
{
"id": "Z2lkOi8vb3BzbGV2ZWwvVGFnLzYwMTgwNzMw",
"key": "secondkey",
"value": "rofl"
}
]
```
If no tags exist, should …

make `get tags` alway require a `key`, add `list tags` command to fetch all keys

---

.changes/unreleased/Feature-20231004-142513.yaml
src/cmd/tag.go

Add `infra` as a type when managing tags. Otherwise users would have to type out `--type=InfrastructureResource`
```
opslevel list tag --type=infra <infra-ID>
```
```
opslevel get tag --type=infra Z2lkOi8vb3BzbGV2ZWwvRW50aXR5T2JqZWN0LzU1OTczOA neat-key-2
[
{
"id": "Z2lkOi8vb3BzbGV2ZWwvVGFnLzYxMjYyNDUw",
"key": "neat-key-2",
"value": "neat-value-2"
}
]
opslevel list tag --type=infra Z2lkOi8vb3BzbGV2ZWwvRW50aXR5T2JqZWN0LzU1OTczOA
[
{
"id": "Z2lkOi8vb3BzbGV2ZWwvVGFnLzYxMjYyNDUw",
"key": "neat-key-2",
"value": "neat-value-2"
}
]
```

allow "infra" when managing infra tags

---

src/cmd/scorecard.go

[#71](https://github.com/OpsLevel/team-platform/issues/71)
Update scorecard example docs to include `AffectsOverallServiceLevels` for scorecard create and update.
`opslevel create scorecard -f sc.yaml` where `sc.yaml` looks very close to example in command docs.
Update `sc.yaml` to switch `affectsOverallServiceLevels: false` to `affectsOverallServiceLevels: true`
`opslevel update scorecard <scorecard-ID> -f sc.yaml`

update scorecard example docs to include affectsOverallServiceLevels

---

.changes/unreleased/Refactor-20231020-134153.yaml
src/cmd/service.go
src/cmd/terraform.go

https://github.com/OpsLevel/opslevel-go/issues/276
```
$ cat service.yml
name: "some new service from CLI"
description: "some new service created on CLI"
product: "whatever"
language: "ruby"
tier: "tier_2"
framework: "rails"
owner:
alias: "platform"%
$ opslevel create service -f service.yml
"Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS84MjA1OQ"
$ cat service_update.yml
id: "Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS84MjA1OQ"
description: "some new service created on CLI - now updated"
owner:
id: "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xMTEwOA"%
$ opslevel update service -f service_update.yml
```

deprecate ownerAlias

---

.changes/unreleased/Feature-20231030-150050.yaml
.changes/unreleased/Removed-20231030-150005.yaml
src/cmd/team.go

[#130](https://github.com/OpsLevel/team-platform/issues/130)
Update example docs for `team create` and `team update` commands.
Update `opslevel.TeamCreateInput` to update `ParentTeam` field instead of deprecated `Group` field
1. Create a `my-team.csv` file:
```csv
Name,Manager,Responsibilities,ParentTeam
Team Fresh Water,samuel@example.com,Makes Tools,go_team
Team Salt Water,saul@example.com,Dev Work,QA
```
2. Run `opslevel import teams -f my-team.csv`
3. Create a `my-team.yaml` file:
```yaml
managerEmail: "estuary@example.com"
responsibilities: "mixing it up"
parentTeam:
alias: "Team Brackish Water"
```
4. Run `opslevel create team angler-test-team -f my-team.yaml`
5. Update `parentTeam` in `my-team.yaml`
6. Run `opslevel update team angler-test-team -f my-team.yaml`

add Parent Teams to add, create, import of teams

---

.changes/unreleased/Bugfix-20231110-141748.yaml
src/cmd/team.go
src/cmd/user.go

[#145](https://github.com/OpsLevel/team-platform/issues/145)
Update inputs passed to `UserIdentifierInput` to be pointers
```
opslevel create member example_team me@example.com manager
opslevel get team example_team
opslevel create member example_team me@example.com contributor
opslevel get team example_team
opslevel delete member example_team
```

update UserIdentifierInput struct inputs to pointers

---

.changes/unreleased/Bugfix-20231127-171854.yaml
.changes/unreleased/Feature-20231127-171923.yaml
src/cmd/terraform.go

After shipping https://github.com/OpsLevel/terraform-provider-opslevel/pull/144 some customers can be in a state where their terraform Team configs are not using the new `member { }` blocks. This results in Team Memberships not being able to reconcile without kicking all members out of the terraform managed teams.
[Also, the terraform export output is not compatible with the latest TF schema version.](https://registry.terraform.io/providers/OpsLevel/opslevel/0.8.13/docs/resources/team)
Before:
```
resource "opslevel_team" "platform" {
name = "platform"
manager_email = ""
aliases = ["platform"]
}
resource "opslevel_team" "platform_2" {
name = "Platform"
manager_email = ""
aliases = ["platform_2"]
}
```
After (places a line space between resources):
```
resource "opslevel_team" "platform" { …
```

Export Teams and team memberships to Terraform

---

.changes/unreleased/Feature-20231208-102655.yaml
src/cmd/action.go
src/cmd/dependency.go
src/cmd/domain.go
src/cmd/filter.go
src/cmd/input.go
src/cmd/scorecard.go
src/cmd/secret.go
src/cmd/service.go
src/cmd/system.go
src/cmd/team.go
src/cmd/trigger_definition.go
src/cmd/user.go
src/common/client.go

- Consolidate similar readThing() funcs into `readResourceInput()` at [src/cmd/input.go](https://github.com/OpsLevel/cli/compare/db/unify-read-cli-input-to-readResourceInput?expand=1#diff-03faa53a7613111d9e5a128a4cd786a590a5278c48fbde3d50558ffa4e8e902e)
```go
func readResourceInput[T any]() (*T, error) {
readInputConfig()
var evt *T
viper.Unmarshal(&evt)
if err := defaults.Set(evt); err != nil {
return nil, err
}
return evt, nil
}
```
- A change similar to below is applied in multiple places:
```diff
- input, err := readWebhookActionCreateInput()
+ input, err := readResourceInput[opslevel.CustomActionsWebhookActionCreateInput]()
```
- The defunct readThing() funcs were then removed
Manual test commands: 
```bash
TEAM_ID=$(opslevel get team tf_baz | jq .Id | tr -d '"')
opslevel update team …
```

consolidate cli input read funcs into readResourceInput

---

.github/workflows/release.yaml
src/.goreleaser.yml

Update deprecated goreleaser args and setting. See [previous release job](https://github.com/OpsLevel/cli/actions/runs/7250382285/job/19750430459) and search `DEPRECATED`

update deprecated goreleaser args and yml

---

.github/dependabot.yml
.gitignore
.gitmodules
Taskfile.yml

Add [gitsubmodule check](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) to `dependabot` config as an extra reminder to update submodules at the end of the week. This can help ensure the cli stays up to date with the latest opslevel-go code
Setting `branch = main` in `.gitmodules` lets `task setup` use `git submodule update --remote` to always get the latest commit from `main`

add dependabot gitsubmodule check for end of week

---

src/cmd/property.go

Adds an update function, replaces `!ok` with `ok`
```
$ cat dropdown.yaml
name: pd
schema:
enum: ["red", "green", "blue"]
type: string
$ o create property-definition -f dropdown.yaml
Z2lkOi8vb3BzbGV2ZWwvUHJvcGVydGllczo6RGVmaW5pdGlvbi8xNzk
$ o get property-definition pd
{
"aliases": [
"pd"
],
"id": "Z2lkOi8vb3BzbGV2ZWwvUHJvcGVydGllczo6RGVmaW5pdGlvbi8xNzk",
"name": "pd",
"description": "",
"displaySubtype": "",
"displayType": "DROPDOWN",
"propertyDisplayStatus": "visible",
"schema": "{\"enum\":[\"red\",\"green\",\"blue\"],\"type\":\"string\"}"
}
```
```
$ cat dropdown_edit.yaml
name: color picker
description: pick a color
schema:
enum: ["red", "green", "blue", "yellow", "purple"]
type: string
$ o update property-definition pd -f dropdown_edit.yaml
{
"aliases": [
"pd",
"color_picker"
], …
```

Add update command to property definitions

---

.changes/unreleased/Feature-20231221-160003.yaml
src/cmd/property.go

Manage PropertyDefinitions with the cli
```bash
opslevel create property-definition -f <(opslevel example property-definition)
opslevel get property-definition <ID>
opslevel list property-definitions
opslevel delete property-definition <ID>
```

add create,get,list,delete PropertyDefinitions capabilities

---

.changes/unreleased/Feature-20231227-145903.yaml
src/cmd/property.go

As part of https://github.com/OpsLevel/product/issues/10
```
~/repos/cli/src ta/list-service-props ❯ o list property computer                                                                                   Ruby 3.0.0 02:23:14 PM
DEFINITION_ID                                            VALUE                                                                                                                       LEN_VALIDATION_ERRORS  
Z2lkOi8vb3BzbGV2ZWwvUHJvcGVydGllczo6RGVmaW5pdGlvbi8xODA  "blue"                                                                                                                      0
Z2lkOi8vb3BzbGV2ZWwvUHJvcGVydGllczo6RGVmaW5pdGlvbi8xODI …
```

Add support for listing properties assigned on a service

---

.changes/unreleased/Feature-20231227-110844.yaml
.changes/unreleased/Feature-20231227-114253.yaml
.changes/unreleased/Feature-20231227-145903.yaml
src/cmd/assign.go
src/cmd/property.go
src/go.mod
src/go.sum

[#10](https://github.com/OpsLevel/product/issues/10)
Added `assign` and `unassign` commands.
Add `PropertyInput` to example commands so 
```bash
opslevel example property > my-prop.yaml
opslevel assign property -f my-prop.yaml
opslevel get property owner-alias property-id
opslevel unassign property owner-alias property-id
```

add assign command, can assign property to services

---

.changes/unreleased/Bugfix-20231229-130258.yaml
.changes/unreleased/Bugfix-20231229-130331.yaml
.gitignore
src/cmd/action.go
src/cmd/trigger_definition.go

https://github.com/OpsLevel/opslevel-go/pull/343
https://github.com/OpsLevel/team-platform/issues/158
\*Can unset an optional ID by using `id: ""`, can unset an optional IdentifierInput by using
```
identifierField:
id: null
alias: null
```
```
$ o example service
name: Hello World
product: OSS
description: Hello World Service
language: Go
framework: fasthttp
tierAlias: tier_4
ownerInput:
alias: Platform
lifecycleAlias: beta
parent:
alias: Engineering
```
Create the service with owner
```
$ cat create.yaml
name: SVC from CLI
product: OSS
description: Hello World Service
language: Go
framework: fasthttp
tierAlias: tier_4
ownerInput:
alias: platform
lifecycleAlias: beta
$ o create service -f create.yaml
"Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS85MjYwMw"
```
Change some property, owner should be …

CLI - allow unsetting optional references (IdentifierInput changes)

---

.changes/unreleased/Bugfix-20240105-154208.yaml
src/cmd/check.go
src/cmd/infra.go

The [defaults package](https://pkg.go.dev/github.com/creasty/defaults#section-readme) is used in CLI and it will set everything that is not populated in a struct to what's in the `default` tag. Currently in opslevel-go the `default` tag is set to so we can show examples, but we should probably use something else. CLI is affected because we have `defaults.Set()` calls.
Affected parts of CLI:
1. [CheckInput](https://github.com/OpsLevel/cli/blob/f66d7ccccfcef56c7a4fcdec7b7a4d969a911950/src/cmd/check.go#L447-L451) - not a problem since there's no `default` tags and the struct is defined in CLI (for some reason.)
2. [DeployEvent](https://github.com/OpsLevel/cli/blob/f66d7ccccfcef56c7a4fcdec7b7a4d969a911950/src/cmd/deploy.go#L38-L48) - not a problem since there's only one `default` tag and it's …

Prevent harmful usage of `defaults.Set()`

---

src/cmd/alias.go
src/cmd/check.go
src/cmd/input.go
src/cmd/system.go
src/cmd/user.go

https://github.com/OpsLevel/team-platform/issues/154 - reduce usage of readInputConfig
Basically I went through all the review comments in `src/cmd/*.go` and `src/common/*.go` to see what could be fixed easily. Found that deploys needs more attention [so I made a ticket for that.](https://github.com/OpsLevel/team-platform/issues/196)
<details>
```
$ cat sys-update.yaml
name: update 2 lol
description: AAAAAAAAAAAAA
owner: Z2lkOi8vb3BzbGV2ZWwvVGVhbS85NzU5
$ go run main.go update system taimoor_s_orange_system -f sys-update.yaml
Z2lkOi8vb3BzbGV2ZWwvRW50aXR5T2JqZWN0Lzc4OTg3Mw
$ opslevel get system taimoor_s_orange_system
"Name": "update 2 lol",
"Description": "AAAAAAAAAAAAA",
"HTMLUrl": "https://app.opslevel.com/catalog/systems/update_2_lol",
"Owner": {
"OnTeam": {
"alias": "platform",
"id": …
```

Small fixes | Cut down on number of `TODO` comments

---

.changes/unreleased/Bugfix-20240123-093822.yaml
README.md
src/Dockerfile

https://github.com/OpsLevel/team-platform/issues/200
```
$ GOOS=linux GOARCH=arm64 go build -o opslevel .
```

Use ubuntu noble provided `jq` version 1.7.1 in Dockerfile

---

.golangci.yml
src/cmd/action.go
src/cmd/graphql.go
src/cmd/import.go
src/cmd/tag.go
src/cmd/user.go

Depends on https://github.com/OpsLevel/cli/pull/241

Re-enable linters in CLI

---

src/cmd/maturity.go

[263](https://github.com/OpsLevel/team-platform/issues/263)
Minor bugfix. Depends on [upstream opslevel-go fixes](https://github.com/OpsLevel/opslevel-go/pull/381)
```bash
opslevel list services maturity -o csv > service_maturity.csv
```

fix bug in list services maturity cmd

---

.changes/unreleased/Feature-20240426-095741.yaml
src/cmd/repository.go

[CLI feature - ability to get list of hidden repositories](https://github.com/OpsLevel/team-platform/issues/226)
Dependent on [upstream opslevel-go PR](https://github.com/OpsLevel/opslevel-go/pull/392)
```bash
opslevel list repos --hidden | wc -l
27
opslevel list repos | wc -l
2227
```

add "--hidden" flag to list respositories command

---

.changes/unreleased/Bugfix-20240523-114929.yaml
src/cmd/deploy.go

Part of https://github.com/OpsLevel/team-platform/issues/368 (GitLab CD integration)
While testing the CLI to create deploys for the GitLab CI integration I not all arguments that can be used for `opslevel create deploy` are supported as environment variables, which is confusing. **According to the help menu env vars should be supported for each field.**
Before: 
```
$ OL_DRY_RUN=true OL_COMMIT_SHA=sha123 OL_COMMIT_MESSAGE=msg123 OL_DEDUP_ID=ded123 OL_DEPLOY_NUMBER=num123 OL_DEPLOY_URL=reddit.com OL_DEPLOYER_EMAIL=taimoor@reddit.com OL_DEPLOYER_NAME=taimoor123 OL_ENVIRONMENT=env123 OL_GIT_PATH='./' OL_DESCRIPTION=desc123 OL_SERVICE=service-alias-here ./opslevel create deploy -i google.com -f .
11:55AM INF {"service":"","deployer":{"email":"taimoor@reddit.com","name":"taimoor123"},"deployed …
```

bugfix - support all environment variables when using `opslevel create deploy`

---

.changes/unreleased/Bugfix-20240718-095431.yaml
src/cmd/service.go

[Regression with update service command](https://github.com/OpsLevel/cli/issues/302)
Stop updating omitted fields (nil in this case) and only set fields to `null` if string is an empty string or `null`

opslevel update service command correctly updates fields

---

.changes/unreleased/Dependency-20240801-123439.yaml
.changes/unreleased/Dependency-20240801-123607.yaml
src/go.mod
src/go.sum

bump opslevel-go version to v2024.8.1, bump module go to 1.22

---

README.md
install.sh

Related to [report-deploy-github-action PR](https://github.com/OpsLevel/report-deploy-github-action/pull/56)
Add install script to download and install `cli` executable. Add curl install instructions to README
```bash
curl -sLS https://raw.githubusercontent.com/OpsLevel/cli/db/install-script/install.sh | sudo sh
```

add install script to curl install OpsLevel cli

---

.changes/unreleased/Feature-20240815-103102.yaml
README.md
install.sh
src/cmd/user.go

[As an End User, I can use filtering on the account users listing](https://github.com/OpsLevel/team-platform/issues/202)
```bash
David    david+pat@opslevel.com    Z2lkOi8vb3BzbGV2ZWwvVXNlci8yNTg5MA  
Deact    deact+pat@opslevel.com    Z2lkOi8vb3BzbGV2ZWwvVXNlci8zMjU4MA  
Kyle     kyle+pat@opslevel.com     Z2lkOi8vb3BzbGV2ZWwvVXNlci8yNTg5Mg  
Taimoor  taimoor+pat@opslevel.com  Z2lkOi8vb3BzbGV2ZWwvVXNlci8yNTg5MQ  
```
```bash
David    david+pat@opslevel.com    Z2lkOi8vb3BzbGV2ZWwvVXNlci8yNTg5MA  
Kyle     kyle+pat@opslevel.com     Z2lkOi8vb3BzbGV2ZWwvVXNlci8yNTg5Mg  
Taimoor  taimoor+pat@opslevel.com  Z2lkOi8vb3BzbGV2ZWwvVXNlci8yNTg5MQ  
```

add --ignore-deactivated flag to list user cmd

---

.changes/unreleased/Bugfix-20240819-163947.yaml
src/cmd/graphql.go

[Error: error parsing variable 'owner=platform' | %!w(<nil>)](https://github.com/OpsLevel/cli/issues/320)

graphql cmd correctly handles errors with field args

---

.changes/unreleased/Feature-20240930-130549.yaml
.changes/unreleased/Feature-20240930-150305.yaml
Taskfile.yml
src/cmd/user.go

Resolves [#463](https://github.com/OpsLevel/team-platform/issues/463)

added --skip-send-invite flag to "create user" cmd

---

.changes/unreleased/Feature-20250312-122543.yaml
src/cmd/deploy.go

Resolves #
Unable to specify the `status` field in a deploy event
Add the ability to set the status field with either `--status=success` or `export OPSLEVEL_STATUS=success`

Add deploy status

---

.gitignore

If you build the CLI this is the path it produces, would be nice if that didn't produce a git diff.

Ignore built binary path

---

CONTRIBUTING.md

Resolves #
The CONTRIBUTING.md was too high level and beginner friendly for more experianced devs.  Additionally the document hadn't really been touched since the inception of the CLI
Rewrite the document for more internal use while still being relevant for external contributors.  Add more information around the project architecture, how to get started, what helpers have been added to the repo and generally just have a better flow / structure.

overhaul contributing based on feedback from evan

---

Taskfile.yml

Resolves #
`task setup` will checkout/update the submodule to the latest commit on the remote branch (I'm guessing main) instead of what's been "pinned" / set 
Don't use `--remote` [docs](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt---remote)

drop --remote flag from submodule setup, use --recursive Just In Case

---

src/cmd/mcp.go

This requires creating a separate graphql client, but we only do that if we are running the MCP server so the overhead is minimal.

Add 'mcp' to mcp graphql UA

---

.github/workflows/security.yml
.github/workflows/tests-integration.yml
.github/workflows/tests.yml

Potential fix for [https://github.com/OpsLevel/cli/security/code-scanning/11](https://github.com/OpsLevel/cli/security/code-scanning/11)
To fix this problem, explicitly set the `permissions` for the workflow, limiting the `GITHUB_TOKEN` permissions granted to jobs. The best way is to add a `permissions:` block at the root level of the workflow (above `jobs:`), specifying the minimal required permissions. In this case, likely only `contents: read` is required—a conservative and safe default. This prevents excessive access, minimizing risk while preserving current functionality. To fix this, insert:
```yaml
permissions:
contents: read
```
after the workflow `name`, events (`on:`), and before `jobs:`.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 11: Workflow does not contain permissions

---

.github/workflows/reports.yml

Potential fix for [https://github.com/OpsLevel/cli/security/code-scanning/9](https://github.com/OpsLevel/cli/security/code-scanning/9)
The best way to fix this issue is to explicitly specify the `permissions` block at the root of the workflow YAML to restrict the default permissions granted to the GITHUB_TOKEN. Since the jobs only read repository contents (via `actions/checkout`) and do not modify anything, the workflow should restrict permissions to `contents: read`, which is the safest minimum. Place the following block at the root, immediately after the workflow `name` (line 1), and before the `on:` field (line 4), in the `.github/workflows/reports.yml` file:
```yaml
permissions:
contents: read
```
This ensures that unless individual jobs or steps override it, the workflow will only …

Potential fix for code scanning alert no. 9: Workflow does not contain permissions
