OpsLevel/cli

changes/unreleased/Feature-20220411-215151.yaml, src/cmd/group.go, src/common/helpers.go
@eochoa260 - There was alot wrong with CUD functionality in opslevel-go.  I setup a meeting to go over it.
=> implement CUD for groups

.github/workflows/release-v2.yml
This should just blow away the release and tag if the change markdown notes exist for the tag
=> Fix release to be more idempotent

.changes/unreleased/Feature-20220630-220013.yaml, src/cmd/maturity.go
=> Add cmd for service maturity levels

.changes/unreleased/Feature-20220803-140502.yaml, src/cmd/policy.go
Opening PR to try to get it reviewed as I go since I'll be OOO tomorrow.
=> Adding function to read files in policies

src/cmd/domain.go, src/cmd/group.go, src/common/client.go
Dependent on https://github.com/OpsLevel/opslevel-go/pull/178 getting merged first.
=> Add domain commands

.changes/unreleased/Feature-20230411-161914.yaml, src/cmd/domain.go, src/cmd/group.go, src/cmd/system.go, src/go.mod, src/go.sum
Don't merge until the feature is GA
=> Start Feature Branch for Domains and Systems

Taskfile.yml, src/cmd/graphql.go, src/cmd/root.go
Added Taskfile.yml that defines tasks to format and test code.
- `gofmt -w .` auto fixed formatting
- `commit` renamed `currentCommit` to appease `go vet`
=> add Taskfile, fix formatting

.changes/unreleased/Feature-20230726-203809.yaml, src/cmd/filter.go
We can't create filters with predicates using YAML and can't update filters at all.
Update `create filter -f ...` to allow a file argument, add `update filter $FILTER_ID -f ...` command.
Setup: I added these 2 lines before the graphql calls and created 2 yaml files for create/update. I added these 2 lines before the graphql call to ensure files are being read correctly.
Can create a filter using YAML file:
```
$ go run main.go create filter -f create_filter.yaml
&{Name:Tier 1 apps using RDS Predicates:[{Key:tier_index KeyData: Type:equals Value:1} {Key:tags KeyData:db Type:equals Value:rds}] Connective:and}
```
Can update a filter using YAML file, by providing `id` as the first argument to the command:
```
$ go run main.go update filter Z2lkOi8vb3BzbGV2ZWwvRmlsdGVyLzIzNTk -f …
```
=> Create and update filters using YAML

.changes/unreleased/Dependency-20230728-112413.yaml, src/go.mod, src/go.sum
=> Update opslevel-go to latest

src/cmd/service.go
=> fix how services are assigned tags

.changes/unreleased/Feature-20230818-114750.yaml, .changes/unreleased/Feature-20230821-143107.yaml, src/cmd/scorecard.go
https://github.com/OpsLevel/team-platform/issues/32
Relies on https://github.com/OpsLevel/opslevel-go/pull/233
---
```
$ cat sc_create.yaml
name: "new scorecard"
description: "a newly created scorecard"
ownerId: "Z2lkOi8vb3BzbGV2ZWwvVGVhbS84ODMy"%                                                                                                                                                              
$ cat sc_update.yaml
name: "updated scorecard"
description: "just updated this scorecard"
ownerId: "Z2lkOi8vb3BzbGV2ZWwvVGVhbS82OTE"%                                                                                                                                                               
$ opslevel create scorecard -f sc_create.yaml
created scorecard: Z2lkOi8vb3BzbGV2ZWwvUnVicmljLzY2Nw …
```
=> Scorecard Support

src/cmd/input.go
Address case where command seems to hang - but really it's waiting for input from an interactive tty
=> print message when input coming from interactive tty

src/cmd/input.go
The commit didn't go though and I rushed the merge
=> quickfix missed in previous commit

src/cmd/graphql.go
=> update default operationName for raw query to empty

CONTRIBUTING.md
=> Fixes typo in contribution.md

.changes/unreleased/Removed-20231113-105847.yaml, src/cmd/group.go, src/cmd/repository.go, src/cmd/service.go, src/cmd/team.go, src/common/helpers.go
```bash
opslevel get repository <ID>
opslevel get service <ID>
opslevel get team platform
```
=> drop func IsID() from common, exists in opslevel-go

.changes/unreleased/Feature-20231211-142515.yaml, .changes/unreleased/Feature-20231211-144222.yaml, src/cmd/property.go
Postpone property definition features for now
=> comment out property definitions for now

.github/workflows/tests.yml
=> use go version in go.mod in test workflow

.github/workflows/tests.yml
For PRs, run `Tests` workflow only when `*.go` files are updated
=> update tests workflow to run only when go files are updated

.github/workflows/release.yaml, .github/workflows/tests.yml
=> add cache to CI

src/go.mod, src/go.sum
=> update opslevel-go release version

.github/workflows/release.yaml
=> add task has-latest-opslevel-go to release workflow

src/cmd/integration.go
Looks like we missed adding this command way back when.
Still needs to be tested
=> Add missing integration commands

opslevel.yml
=> update lifecycle stage

src/cmd/terraform.go
Simply fixes CI on main
This was blocking https://github.com/OpsLevel/team-platform/issues/368 / https://github.com/OpsLevel/cli/pull/283
=> bugfix - fix CI error on `main` branch by removing `**Predicate`

src/cmd/service.go
[Hard to understand what opslevel update service can actually modify](https://github.com/OpsLevel/cli/issues/303)
=> update service command help docs

.changes/unreleased/Feature-20240723-103058.yaml, .changes/unreleased/Feature-20240725-105130.yaml, src/cmd/service.go
[Return service's custom properties in the json output](https://github.com/OpsLevel/team-platform/issues/427)
Run `opslevel get service sample_mobile_app`
```json
{
"description": "Our mobile app. Find us in any App Store!",
"framework": "Flutter",
"htmlUrl": "https://app.opslevel.com/services/sample_mobile_app",
"id": "Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS85MzMzMA",
"aliases": [
"sample_mobile_app"
],
"language": "Dart",
"name": "(Sample) Mobile App",
"Dependencies": {
"Edges": [
{
"Id": "Z2lkOi8vb3BzbGV2ZWwvU2VydmljZURlcGVuZGVuY3kvMzE4MjE0",
"Locked": false,
"Node": {
"id": "Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS85MzMyOA",
"aliases": [
"Shopping Cart Service",
"ShoppingCartService",
"cart",
"sample_shopping_cart_service"
]
},
"Notes": ""
}
],
"PageInfo": {
"HasNextPage": false,
"HasPreviousPage": …
```
=> opslevel get and list service commands prints properties data

.github/workflows/release.yaml
=> bump version of report-deploy-github-action in release workflow

src/.goreleaser.yml
`goreleaser release --snapshot --clean`
=> fix deprecated field in goreleaser config

.changes/unreleased/Feature-20241008-114223.yaml, src/cmd/integration.go
Resolves [#506](https://github.com/OpsLevel/team-platform/issues/506)
=> added new reactivate integration command

.changes/unreleased/Bugfix-20241105-105405.yaml
Resolves [#515](https://github.com/OpsLevel/team-platform/issues/515)
=> add service owner field changie, update opslevel-go submodule hash

src/cmd/service.go
=> list service prints empty JSON string when none found

.changes/unreleased/Bugfix-20241106-120713.yaml, src/cmd/check.go
Resolves [#536](https://github.com/OpsLevel/team-platform/issues/536)
=> verify check "kind" in config before create and update

install.sh
=> install script can install known versions of cli

.github/workflows/release.yaml, .github/workflows/tests-integration.yml, .github/workflows/tests.yml
=> add missing cache-dependency-path in setup-go GH action

README.md
Resolves nothing.
The tool was listed as "beta" despite being out for a while and being pretty stable.
Removes leftover text from readme.
=> Removes beta warning

src/run.sh
This works for me with hot-reloading the MCP server in Claude Desktop, with the following config:
```
{                                                                                
"mcpServers": {                                                                
"opslevel": {                                                                
"command": "/Users/eapache/src/github.com/OpsLevel/cli/src/run.sh",        
"args": ["beta", "mcp"],                                                   
"env": {                                                                   
"OPSLEVEL_API_URL": "http://localhost:3000",                             
"OPSLEVEL_API_TOKEN": "XXX",            
"GOPATH": "/Users/eapache",                                              
"HOME": "/Users/eapache" …
```
=> Add run script for Claude Desktop hot-reloading
